image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build_test

build_test:
    stage: build_test
    script:
        - "cd source  &&  dotnet build -c Release  &&  dotnet test -c Release --no-build"
