image: microsoft/dotnet:latest

stages:
    - build_test

build_test:
    stage: build_test
    script:
        - "cd source  &&  dotnet build -c Release  &&  dotnet test -c Release --no-build"
