using System;
using System.Collections.Generic;
using System.Linq;

// ReSharper disable InconsistentNaming
// ReSharper disable IdentifierTypo

#pragma warning disable IDE1006 // Naming Styles

namespace MikhailKhalizev.Processor.x86.InstructionDecode
{
    // 253665-sdm-vol-1.pdf
    // APPENDIX A EFLAGS CROSS-REFERENCE.
    // Table A-2. EFLAGS Cross-Reference.
    public static class EflagsCrossReference
    {
        public static IReadOnlyDictionary<InstructionUniqueName, Item> FlagsByInstruction { get; }

        static EflagsCrossReference()
        {
            var items = new Item[]
            {
                new Item(InstructionUniqueName.aaa, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.tm, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.aad, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.aam, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.aas, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.tm, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.adc, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.tm, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.add, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.and, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.arpl, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.bound, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.bsf, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.bsr, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.bswap, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.bt, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.bts, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.btr, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.btc, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.call, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cbw, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.clc, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cld, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cli, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.clts, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cmc, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cmovcc, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cmp, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cmps, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cmpxchg, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cmpxchg8b, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.comisd, CodesDescribingFlags.Zero, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.comiss, CodesDescribingFlags.Zero, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cpuid, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.cwd, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.daa, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.tm, CodesDescribingFlags.m, CodesDescribingFlags.tm, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.das, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.tm, CodesDescribingFlags.m, CodesDescribingFlags.tm, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.dec, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.div, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.enter, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.esc, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.fcmovcc, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.fcomi, CodesDescribingFlags.Zero, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.fcomip, CodesDescribingFlags.Zero, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.fucomi, CodesDescribingFlags.Zero, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.fucomip, CodesDescribingFlags.Zero, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.hlt, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.idiv, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.imul, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.@in, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.inc, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.ins, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.@int, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.into, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.invd, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.invlpg, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.ucomisd, CodesDescribingFlags.Zero, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.ucomiss, CodesDescribingFlags.Zero, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.iret, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.t, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.jcc, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.jcxz, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.jmp, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lahf, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lar, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lds, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.les, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lss, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lfs, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lgs, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lea, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.leave, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lgdt, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lidt, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lldt, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lmsw, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.@lock, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lods, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.loop, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.loope, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.loopne, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.lsl, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.ltr, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.monitor, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.mwait, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.mov, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.mov_cr, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.mov_dr, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                // TODO new Item(InstructionUniqueName.mov test, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.movs, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.movsx, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.movzx, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.mul, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.neg, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.nop, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.not, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.or, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.@out, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.outs, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.pop, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.popa, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.popf, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.push, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.pusha, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.pushf, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                // TODO  new Item(InstructionUniqueName.rcl / rcr 1, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.tm, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                // TODO  new Item(InstructionUniqueName.rcl / rcr count, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.tm, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.rdmsr, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.rdpmc, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.rdtsc, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.rep, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.repe, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.repne, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.ret, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                // TODO  new Item(InstructionUniqueName.rol / ror 1, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                // TODO  new Item(InstructionUniqueName.rol / ror count, CodesDescribingFlags.Undefined, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.rsm, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m),
                new Item(InstructionUniqueName.sahf, CodesDescribingFlags.Blank, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.r, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                // TODO  new Item(InstructionUniqueName.sal / sar / shl / shr 1, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                // TODO  new Item(InstructionUniqueName.sal / sar / shl / shr count, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.sbb, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.tm, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.scas, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.setcc, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.sgdt, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.sidt, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.sldt, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.smsw, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.shld, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.shrd, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.stc, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.One, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.std, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.One, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.sti, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.One, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.stos, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.t, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.str, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.sub, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.test, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.ud, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.verr, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                // TODO new Item(InstructionUniqueName.verrw, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.wait, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.wbinvd, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.wrmsr, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.xadd, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.xchg, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.xlat, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
                new Item(InstructionUniqueName.xor, CodesDescribingFlags.Zero, CodesDescribingFlags.m, CodesDescribingFlags.m, CodesDescribingFlags.Undefined, CodesDescribingFlags.m, CodesDescribingFlags.Zero, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank, CodesDescribingFlags.Blank),
            };

            FlagsByInstruction = items.ToDictionary(x => x.Instruction, x => x);
        }

        public class Item
        {
            public Item(InstructionUniqueName instruction, CodesDescribingFlags of, CodesDescribingFlags sf, CodesDescribingFlags zf, CodesDescribingFlags af, CodesDescribingFlags pf, CodesDescribingFlags cf, CodesDescribingFlags tf, CodesDescribingFlags @if, CodesDescribingFlags df, CodesDescribingFlags nt, CodesDescribingFlags rf)
            {
                Instruction = instruction;
                this.of = of;
                this.sf = sf;
                this.zf = zf;
                this.af = af;
                this.pf = pf;
                this.cf = cf;
                this.tf = tf;
                this.@if = @if;
                this.df = df;
                this.nt = nt;
                this.rf = rf;
            }

            public InstructionUniqueName Instruction { get; }
            public CodesDescribingFlags of { get; }
            public CodesDescribingFlags sf { get; }
            public CodesDescribingFlags zf { get; }
            public CodesDescribingFlags af { get; }
            public CodesDescribingFlags pf { get; }
            public CodesDescribingFlags cf { get; }
            public CodesDescribingFlags tf { get; }
            public CodesDescribingFlags @if { get; }
            public CodesDescribingFlags df { get; }
            public CodesDescribingFlags nt { get; }
            public CodesDescribingFlags rf { get; }
        }

        // Table A-1. Codes Describing Flags
        [Flags]
        public enum CodesDescribingFlags
        {
            /// <summary>
            /// Instruction tests flag.
            /// </summary>
            t = 1 << 0,

            /// <summary>
            /// Instruction modifies flag (either sets or resets depending on operands).
            /// </summary>
            m = 1 << 1,

            tm = t | m,

            /// <summary>
            /// Instruction resets flag.
            /// </summary>
            Zero = 1 << 2,

            /// <summary>
            /// Instruction sets flag.
            /// </summary>
            One = 1 << 3,

            /// <summary>
            /// Instruction's effect on flag is undefined.
            /// </summary>
            Undefined = 1 << 4,

            /// <summary>
            /// Instruction restores prior value of flag.
            /// </summary>
            r = 1 << 5,

            /// <summary>
            /// Instruction does not affect flag.
            /// </summary>
            Blank = 1 << 6
        }
    }
}