using System;
using MikhailKhalizev.Processor.x86.BinToCSharp;

namespace MikhailKhalizev.Max.Program
{
    public partial class RawProgram
    {
        [MethodInfo("7655d06c-5a85-417f-aaef-57b59f385295")]
        public void Method_0000_9076()
        {
            ii(0x9076, 1);    int3();                                   /* int3 */
            ii(0x9077, 1);    int3();                                   /* int3 */
            ii(0x9078, 1);    int3();                                   /* int3 */
            ii(0x9079, 1);    int3();                                   /* int3 */
            ii(0x907a, 1);    int3();                                   /* int3 */
            ii(0x907b, 1);    int3();                                   /* int3 */
            ii(0x907c, 1);    int3();                                   /* int3 */
            ii(0x907d, 1);    int3();                                   /* int3 */
            ii(0x907e, 1);    int3();                                   /* int3 */
            ii(0x907f, 1);    int3();                                   /* int3 */
            ii(0x9080, 1);    int3();                                   /* int3 */
            ii(0x9081, 1);    int3();                                   /* int3 */
            ii(0x9082, 1);    int3();                                   /* int3 */
            ii(0x9083, 1);    int3();                                   /* int3 */
            ii(0x9084, 1);    int3();                                   /* int3 */
            ii(0x9085, 1);    int3();                                   /* int3 */
            ii(0x9086, 1);    int3();                                   /* int3 */
            ii(0x9087, 1);    int3();                                   /* int3 */
            ii(0x9088, 1);    int3();                                   /* int3 */
            ii(0x9089, 1);    int3();                                   /* int3 */
            ii(0x908a, 1);    int3();                                   /* int3 */
            ii(0x908b, 1);    int3();                                   /* int3 */
            ii(0x908c, 1);    int3();                                   /* int3 */
            ii(0x908d, 1);    int3();                                   /* int3 */
            ii(0x908e, 1);    int3();                                   /* int3 */
            ii(0x908f, 1);    int3();                                   /* int3 */
            ii(0x9090, 1);    int3();                                   /* int3 */
            ii(0x9091, 1);    int3();                                   /* int3 */
            ii(0x9092, 1);    int3();                                   /* int3 */
            ii(0x9093, 1);    int3();                                   /* int3 */
            ii(0x9094, 1);    int3();                                   /* int3 */
            ii(0x9095, 1);    int3();                                   /* int3 */
            ii(0x9096, 1);    int3();                                   /* int3 */
            ii(0x9097, 1);    int3();                                   /* int3 */
            ii(0x9098, 1);    int3();                                   /* int3 */
            ii(0x9099, 1);    int3();                                   /* int3 */
            ii(0x909a, 1);    int3();                                   /* int3 */
            ii(0x909b, 1);    int3();                                   /* int3 */
            ii(0x909c, 1);    int3();                                   /* int3 */
            ii(0x909d, 1);    int3();                                   /* int3 */
            ii(0x909e, 1);    int3();                                   /* int3 */
            ii(0x909f, 1);    int3();                                   /* int3 */
            ii(0x90a0, 1);    int3();                                   /* int3 */
            ii(0x90a1, 1);    int3();                                   /* int3 */
            ii(0x90a2, 1);    int3();                                   /* int3 */
            ii(0x90a3, 1);    int3();                                   /* int3 */
            ii(0x90a4, 1);    int3();                                   /* int3 */
            ii(0x90a5, 1);    int3();                                   /* int3 */
            ii(0x90a6, 1);    int3();                                   /* int3 */
            ii(0x90a7, 1);    int3();                                   /* int3 */
            ii(0x90a8, 1);    int3();                                   /* int3 */
            ii(0x90a9, 1);    int3();                                   /* int3 */
            ii(0x90aa, 1);    int3();                                   /* int3 */
            ii(0x90ab, 1);    int3();                                   /* int3 */
            ii(0x90ac, 1);    int3();                                   /* int3 */
            ii(0x90ad, 1);    int3();                                   /* int3 */
            ii(0x90ae, 1);    int3();                                   /* int3 */
            ii(0x90af, 1);    int3();                                   /* int3 */
            ii(0x90b0, 1);    int3();                                   /* int3 */
            ii(0x90b1, 1);    int3();                                   /* int3 */
            ii(0x90b2, 1);    int3();                                   /* int3 */
            ii(0x90b3, 1);    int3();                                   /* int3 */
            ii(0x90b4, 1);    int3();                                   /* int3 */
            ii(0x90b5, 1);    int3();                                   /* int3 */
            ii(0x90b6, 1);    int3();                                   /* int3 */
            ii(0x90b7, 1);    int3();                                   /* int3 */
            ii(0x90b8, 1);    int3();                                   /* int3 */
            ii(0x90b9, 1);    int3();                                   /* int3 */
            ii(0x90ba, 1);    int3();                                   /* int3 */
            ii(0x90bb, 1);    int3();                                   /* int3 */
            ii(0x90bc, 1);    int3();                                   /* int3 */
            ii(0x90bd, 1);    int3();                                   /* int3 */
            ii(0x90be, 1);    int3();                                   /* int3 */
            ii(0x90bf, 1);    int3();                                   /* int3 */
            ii(0x90c0, 1);    int3();                                   /* int3 */
            ii(0x90c1, 1);    int3();                                   /* int3 */
            ii(0x90c2, 1);    int3();                                   /* int3 */
            ii(0x90c3, 1);    int3();                                   /* int3 */
            ii(0x90c4, 1);    int3();                                   /* int3 */
            ii(0x90c5, 1);    int3();                                   /* int3 */
            ii(0x90c6, 1);    int3();                                   /* int3 */
            ii(0x90c7, 1);    int3();                                   /* int3 */
            ii(0x90c8, 1);    int3();                                   /* int3 */
            ii(0x90c9, 1);    int3();                                   /* int3 */
            ii(0x90ca, 1);    int3();                                   /* int3 */
            ii(0x90cb, 1);    int3();                                   /* int3 */
            ii(0x90cc, 1);    int3();                                   /* int3 */
            ii(0x90cd, 1);    int3();                                   /* int3 */
            ii(0x90ce, 1);    int3();                                   /* int3 */
            ii(0x90cf, 1);    int3();                                   /* int3 */
            ii(0x90d0, 1);    int3();                                   /* int3 */
            ii(0x90d1, 1);    int3();                                   /* int3 */
            ii(0x90d2, 1);    int3();                                   /* int3 */
            ii(0x90d3, 1);    int3();                                   /* int3 */
            ii(0x90d4, 1);    int3();                                   /* int3 */
            ii(0x90d5, 1);    int3();                                   /* int3 */
            ii(0x90d6, 1);    int3();                                   /* int3 */
            ii(0x90d7, 1);    int3();                                   /* int3 */
            ii(0x90d8, 1);    int3();                                   /* int3 */
            ii(0x90d9, 1);    int3();                                   /* int3 */
            ii(0x90da, 1);    int3();                                   /* int3 */
            ii(0x90db, 1);    int3();                                   /* int3 */
            ii(0x90dc, 1);    int3();                                   /* int3 */
            ii(0x90dd, 1);    int3();                                   /* int3 */
            ii(0x90de, 1);    int3();                                   /* int3 */
            ii(0x90df, 1);    int3();                                   /* int3 */
            ii(0x90e0, 1);    int3();                                   /* int3 */
            ii(0x90e1, 1);    int3();                                   /* int3 */
            ii(0x90e2, 1);    int3();                                   /* int3 */
            ii(0x90e3, 1);    int3();                                   /* int3 */
            ii(0x90e4, 1);    int3();                                   /* int3 */
            ii(0x90e5, 1);    int3();                                   /* int3 */
            ii(0x90e6, 1);    int3();                                   /* int3 */
            ii(0x90e7, 1);    int3();                                   /* int3 */
            ii(0x90e8, 1);    int3();                                   /* int3 */
            ii(0x90e9, 1);    int3();                                   /* int3 */
            ii(0x90ea, 1);    int3();                                   /* int3 */
            ii(0x90eb, 1);    int3();                                   /* int3 */
            ii(0x90ec, 1);    int3();                                   /* int3 */
            ii(0x90ed, 1);    int3();                                   /* int3 */
            ii(0x90ee, 1);    int3();                                   /* int3 */
            ii(0x90ef, 1);    int3();                                   /* int3 */
            ii(0x90f0, 1);    int3();                                   /* int3 */
            ii(0x90f1, 1);    int3();                                   /* int3 */
            ii(0x90f2, 1);    int3();                                   /* int3 */
            ii(0x90f3, 1);    int3();                                   /* int3 */
            ii(0x90f4, 1);    int3();                                   /* int3 */
            ii(0x90f5, 1);    int3();                                   /* int3 */
            ii(0x90f6, 1);    int3();                                   /* int3 */
            ii(0x90f7, 1);    int3();                                   /* int3 */
            ii(0x90f8, 1);    int3();                                   /* int3 */
            ii(0x90f9, 1);    int3();                                   /* int3 */
            ii(0x90fa, 1);    int3();                                   /* int3 */
            ii(0x90fb, 1);    int3();                                   /* int3 */
            ii(0x90fc, 1);    int3();                                   /* int3 */
            ii(0x90fd, 1);    int3();                                   /* int3 */
            ii(0x90fe, 1);    int3();                                   /* int3 */
            ii(0x90ff, 1);    int3();                                   /* int3 */
            ii(0x9100, 1);    int3();                                   /* int3 */
            ii(0x9101, 1);    int3();                                   /* int3 */
            ii(0x9102, 1);    int3();                                   /* int3 */
            ii(0x9103, 1);    int3();                                   /* int3 */
            ii(0x9104, 1);    int3();                                   /* int3 */
            ii(0x9105, 1);    int3();                                   /* int3 */
            ii(0x9106, 1);    int3();                                   /* int3 */
            ii(0x9107, 1);    int3();                                   /* int3 */
            ii(0x9108, 1);    int3();                                   /* int3 */
            ii(0x9109, 1);    int3();                                   /* int3 */
            ii(0x910a, 1);    int3();                                   /* int3 */
            ii(0x910b, 1);    int3();                                   /* int3 */
            ii(0x910c, 1);    int3();                                   /* int3 */
            ii(0x910d, 1);    int3();                                   /* int3 */
            ii(0x910e, 1);    int3();                                   /* int3 */
            ii(0x910f, 1);    int3();                                   /* int3 */
            ii(0x9110, 1);    int3();                                   /* int3 */
            ii(0x9111, 1);    int3();                                   /* int3 */
            ii(0x9112, 1);    int3();                                   /* int3 */
            ii(0x9113, 1);    int3();                                   /* int3 */
            ii(0x9114, 1);    int3();                                   /* int3 */
            ii(0x9115, 1);    int3();                                   /* int3 */
            ii(0x9116, 1);    int3();                                   /* int3 */
            ii(0x9117, 1);    int3();                                   /* int3 */
            ii(0x9118, 1);    int3();                                   /* int3 */
            ii(0x9119, 1);    int3();                                   /* int3 */
            ii(0x911a, 1);    int3();                                   /* int3 */
            ii(0x911b, 1);    int3();                                   /* int3 */
            ii(0x911c, 1);    int3();                                   /* int3 */
            ii(0x911d, 1);    int3();                                   /* int3 */
            ii(0x911e, 1);    int3();                                   /* int3 */
            ii(0x911f, 1);    int3();                                   /* int3 */
            ii(0x9120, 1);    int3();                                   /* int3 */
            ii(0x9121, 1);    int3();                                   /* int3 */
            ii(0x9122, 1);    int3();                                   /* int3 */
            ii(0x9123, 1);    int3();                                   /* int3 */
            ii(0x9124, 1);    int3();                                   /* int3 */
            ii(0x9125, 1);    int3();                                   /* int3 */
            ii(0x9126, 1);    int3();                                   /* int3 */
            ii(0x9127, 1);    int3();                                   /* int3 */
            ii(0x9128, 1);    int3();                                   /* int3 */
            ii(0x9129, 1);    int3();                                   /* int3 */
            ii(0x912a, 1);    int3();                                   /* int3 */
            ii(0x912b, 1);    int3();                                   /* int3 */
            ii(0x912c, 1);    int3();                                   /* int3 */
            ii(0x912d, 1);    int3();                                   /* int3 */
            ii(0x912e, 1);    int3();                                   /* int3 */
            ii(0x912f, 1);    int3();                                   /* int3 */
            ii(0x9130, 1);    int3();                                   /* int3 */
            ii(0x9131, 1);    int3();                                   /* int3 */
            ii(0x9132, 1);    int3();                                   /* int3 */
            ii(0x9133, 1);    int3();                                   /* int3 */
            ii(0x9134, 1);    int3();                                   /* int3 */
            ii(0x9135, 1);    int3();                                   /* int3 */
            ii(0x9136, 1);    int3();                                   /* int3 */
            ii(0x9137, 1);    int3();                                   /* int3 */
            ii(0x9138, 1);    int3();                                   /* int3 */
            ii(0x9139, 1);    int3();                                   /* int3 */
            ii(0x913a, 1);    int3();                                   /* int3 */
            ii(0x913b, 1);    int3();                                   /* int3 */
            ii(0x913c, 1);    int3();                                   /* int3 */
            ii(0x913d, 1);    int3();                                   /* int3 */
            ii(0x913e, 1);    int3();                                   /* int3 */
            ii(0x913f, 1);    int3();                                   /* int3 */
            ii(0x9140, 1);    int3();                                   /* int3 */
            ii(0x9141, 1);    int3();                                   /* int3 */
            ii(0x9142, 1);    int3();                                   /* int3 */
            ii(0x9143, 1);    int3();                                   /* int3 */
            ii(0x9144, 1);    int3();                                   /* int3 */
            ii(0x9145, 1);    int3();                                   /* int3 */
            ii(0x9146, 1);    int3();                                   /* int3 */
            ii(0x9147, 1);    int3();                                   /* int3 */
            ii(0x9148, 1);    int3();                                   /* int3 */
            ii(0x9149, 1);    int3();                                   /* int3 */
            ii(0x914a, 1);    int3();                                   /* int3 */
            ii(0x914b, 1);    int3();                                   /* int3 */
            ii(0x914c, 1);    int3();                                   /* int3 */
            ii(0x914d, 1);    int3();                                   /* int3 */
            ii(0x914e, 1);    int3();                                   /* int3 */
            ii(0x914f, 1);    int3();                                   /* int3 */
            ii(0x9150, 1);    int3();                                   /* int3 */
            ii(0x9151, 1);    int3();                                   /* int3 */
            ii(0x9152, 1);    int3();                                   /* int3 */
            ii(0x9153, 1);    int3();                                   /* int3 */
            ii(0x9154, 1);    int3();                                   /* int3 */
            ii(0x9155, 1);    int3();                                   /* int3 */
            ii(0x9156, 1);    int3();                                   /* int3 */
            ii(0x9157, 1);    int3();                                   /* int3 */
            ii(0x9158, 1);    int3();                                   /* int3 */
            ii(0x9159, 1);    int3();                                   /* int3 */
            ii(0x915a, 1);    int3();                                   /* int3 */
            ii(0x915b, 1);    int3();                                   /* int3 */
            ii(0x915c, 1);    int3();                                   /* int3 */
            ii(0x915d, 1);    int3();                                   /* int3 */
            ii(0x915e, 1);    int3();                                   /* int3 */
            ii(0x915f, 1);    int3();                                   /* int3 */
            ii(0x9160, 1);    int3();                                   /* int3 */
            ii(0x9161, 1);    int3();                                   /* int3 */
            ii(0x9162, 1);    int3();                                   /* int3 */
            ii(0x9163, 1);    int3();                                   /* int3 */
            ii(0x9164, 1);    int3();                                   /* int3 */
            ii(0x9165, 1);    int3();                                   /* int3 */
            ii(0x9166, 1);    int3();                                   /* int3 */
            ii(0x9167, 1);    int3();                                   /* int3 */
            ii(0x9168, 1);    int3();                                   /* int3 */
            ii(0x9169, 1);    int3();                                   /* int3 */
            ii(0x916a, 1);    int3();                                   /* int3 */
            ii(0x916b, 1);    int3();                                   /* int3 */
            ii(0x916c, 1);    int3();                                   /* int3 */
            ii(0x916d, 1);    int3();                                   /* int3 */
            ii(0x916e, 1);    int3();                                   /* int3 */
            ii(0x916f, 1);    int3();                                   /* int3 */
            ii(0x9170, 1);    int3();                                   /* int3 */
            ii(0x9171, 1);    int3();                                   /* int3 */
            ii(0x9172, 1);    int3();                                   /* int3 */
            ii(0x9173, 1);    int3();                                   /* int3 */
            ii(0x9174, 1);    int3();                                   /* int3 */
            ii(0x9175, 1);    int3();                                   /* int3 */
            ii(0x9176, 1);    int3();                                   /* int3 */
            ii(0x9177, 1);    int3();                                   /* int3 */
            ii(0x9178, 1);    int3();                                   /* int3 */
            ii(0x9179, 1);    int3();                                   /* int3 */
            ii(0x917a, 1);    int3();                                   /* int3 */
            ii(0x917b, 1);    int3();                                   /* int3 */
            ii(0x917c, 1);    int3();                                   /* int3 */
            ii(0x917d, 1);    int3();                                   /* int3 */
            ii(0x917e, 1);    int3();                                   /* int3 */
            ii(0x917f, 1);    int3();                                   /* int3 */
            ii(0x9180, 1);    int3();                                   /* int3 */
            ii(0x9181, 1);    int3();                                   /* int3 */
            ii(0x9182, 1);    int3();                                   /* int3 */
            ii(0x9183, 1);    int3();                                   /* int3 */
            ii(0x9184, 1);    int3();                                   /* int3 */
            ii(0x9185, 1);    int3();                                   /* int3 */
            ii(0x9186, 1);    int3();                                   /* int3 */
            ii(0x9187, 1);    int3();                                   /* int3 */
            ii(0x9188, 1);    int3();                                   /* int3 */
            ii(0x9189, 1);    int3();                                   /* int3 */
            ii(0x918a, 1);    int3();                                   /* int3 */
            ii(0x918b, 1);    int3();                                   /* int3 */
            ii(0x918c, 1);    int3();                                   /* int3 */
            ii(0x918d, 1);    int3();                                   /* int3 */
            ii(0x918e, 1);    int3();                                   /* int3 */
            ii(0x918f, 1);    int3();                                   /* int3 */
            ii(0x9190, 1);    int3();                                   /* int3 */
            ii(0x9191, 1);    int3();                                   /* int3 */
            ii(0x9192, 1);    int3();                                   /* int3 */
            ii(0x9193, 1);    int3();                                   /* int3 */
            ii(0x9194, 1);    int3();                                   /* int3 */
            ii(0x9195, 1);    int3();                                   /* int3 */
            ii(0x9196, 1);    int3();                                   /* int3 */
            ii(0x9197, 1);    int3();                                   /* int3 */
            ii(0x9198, 1);    int3();                                   /* int3 */
            ii(0x9199, 1);    int3();                                   /* int3 */
            ii(0x919a, 1);    int3();                                   /* int3 */
            ii(0x919b, 1);    int3();                                   /* int3 */
            ii(0x919c, 1);    int3();                                   /* int3 */
            ii(0x919d, 1);    int3();                                   /* int3 */
            ii(0x919e, 1);    int3();                                   /* int3 */
            ii(0x919f, 1);    int3();                                   /* int3 */
            ii(0x91a0, 1);    int3();                                   /* int3 */
            ii(0x91a1, 1);    int3();                                   /* int3 */
            ii(0x91a2, 1);    int3();                                   /* int3 */
            ii(0x91a3, 1);    int3();                                   /* int3 */
            ii(0x91a4, 1);    int3();                                   /* int3 */
            ii(0x91a5, 1);    int3();                                   /* int3 */
            ii(0x91a6, 1);    int3();                                   /* int3 */
            ii(0x91a7, 1);    int3();                                   /* int3 */
            ii(0x91a8, 1);    int3();                                   /* int3 */
            ii(0x91a9, 1);    int3();                                   /* int3 */
            ii(0x91aa, 1);    int3();                                   /* int3 */
            ii(0x91ab, 1);    int3();                                   /* int3 */
            ii(0x91ac, 1);    int3();                                   /* int3 */
            ii(0x91ad, 1);    int3();                                   /* int3 */
            ii(0x91ae, 1);    int3();                                   /* int3 */
            ii(0x91af, 1);    int3();                                   /* int3 */
            ii(0x91b0, 1);    int3();                                   /* int3 */
            ii(0x91b1, 1);    int3();                                   /* int3 */
            ii(0x91b2, 1);    int3();                                   /* int3 */
            ii(0x91b3, 1);    int3();                                   /* int3 */
            ii(0x91b4, 1);    int3();                                   /* int3 */
            ii(0x91b5, 1);    int3();                                   /* int3 */
            ii(0x91b6, 1);    int3();                                   /* int3 */
            ii(0x91b7, 1);    int3();                                   /* int3 */
            ii(0x91b8, 1);    int3();                                   /* int3 */
            ii(0x91b9, 1);    int3();                                   /* int3 */
            ii(0x91ba, 1);    int3();                                   /* int3 */
            ii(0x91bb, 1);    int3();                                   /* int3 */
            ii(0x91bc, 1);    int3();                                   /* int3 */
            ii(0x91bd, 1);    int3();                                   /* int3 */
            ii(0x91be, 1);    int3();                                   /* int3 */
            ii(0x91bf, 1);    int3();                                   /* int3 */
            ii(0x91c0, 1);    int3();                                   /* int3 */
            ii(0x91c1, 1);    int3();                                   /* int3 */
            ii(0x91c2, 1);    int3();                                   /* int3 */
            ii(0x91c3, 1);    int3();                                   /* int3 */
            ii(0x91c4, 1);    int3();                                   /* int3 */
            ii(0x91c5, 1);    int3();                                   /* int3 */
            ii(0x91c6, 1);    int3();                                   /* int3 */
            ii(0x91c7, 1);    int3();                                   /* int3 */
            ii(0x91c8, 1);    int3();                                   /* int3 */
            ii(0x91c9, 1);    int3();                                   /* int3 */
            ii(0x91ca, 1);    int3();                                   /* int3 */
            ii(0x91cb, 1);    int3();                                   /* int3 */
            ii(0x91cc, 1);    int3();                                   /* int3 */
            ii(0x91cd, 1);    int3();                                   /* int3 */
            ii(0x91ce, 1);    int3();                                   /* int3 */
            ii(0x91cf, 1);    int3();                                   /* int3 */
            ii(0x91d0, 1);    int3();                                   /* int3 */
            ii(0x91d1, 1);    int3();                                   /* int3 */
            ii(0x91d2, 1);    int3();                                   /* int3 */
            ii(0x91d3, 1);    int3();                                   /* int3 */
            ii(0x91d4, 1);    int3();                                   /* int3 */
            ii(0x91d5, 1);    int3();                                   /* int3 */
            ii(0x91d6, 1);    int3();                                   /* int3 */
            ii(0x91d7, 1);    int3();                                   /* int3 */
            ii(0x91d8, 1);    int3();                                   /* int3 */
            ii(0x91d9, 1);    int3();                                   /* int3 */
            ii(0x91da, 1);    int3();                                   /* int3 */
            ii(0x91db, 1);    int3();                                   /* int3 */
            ii(0x91dc, 1);    int3();                                   /* int3 */
            ii(0x91dd, 1);    int3();                                   /* int3 */
            ii(0x91de, 1);    int3();                                   /* int3 */
            ii(0x91df, 1);    int3();                                   /* int3 */
            ii(0x91e0, 1);    int3();                                   /* int3 */
            ii(0x91e1, 1);    int3();                                   /* int3 */
            ii(0x91e2, 1);    int3();                                   /* int3 */
            ii(0x91e3, 1);    int3();                                   /* int3 */
            ii(0x91e4, 1);    int3();                                   /* int3 */
            ii(0x91e5, 1);    int3();                                   /* int3 */
            ii(0x91e6, 1);    int3();                                   /* int3 */
            ii(0x91e7, 1);    int3();                                   /* int3 */
            ii(0x91e8, 1);    int3();                                   /* int3 */
            ii(0x91e9, 1);    int3();                                   /* int3 */
            ii(0x91ea, 1);    int3();                                   /* int3 */
            ii(0x91eb, 1);    int3();                                   /* int3 */
            ii(0x91ec, 1);    int3();                                   /* int3 */
            ii(0x91ed, 1);    int3();                                   /* int3 */
            ii(0x91ee, 1);    int3();                                   /* int3 */
            ii(0x91ef, 1);    int3();                                   /* int3 */
            ii(0x91f0, 1);    int3();                                   /* int3 */
            ii(0x91f1, 1);    int3();                                   /* int3 */
            ii(0x91f2, 1);    int3();                                   /* int3 */
            ii(0x91f3, 1);    int3();                                   /* int3 */
            ii(0x91f4, 1);    int3();                                   /* int3 */
            ii(0x91f5, 1);    int3();                                   /* int3 */
            ii(0x91f6, 1);    int3();                                   /* int3 */
            ii(0x91f7, 1);    int3();                                   /* int3 */
            ii(0x91f8, 1);    int3();                                   /* int3 */
            ii(0x91f9, 1);    int3();                                   /* int3 */
            ii(0x91fa, 1);    int3();                                   /* int3 */
            ii(0x91fb, 1);    int3();                                   /* int3 */
            ii(0x91fc, 1);    int3();                                   /* int3 */
            ii(0x91fd, 1);    int3();                                   /* int3 */
            ii(0x91fe, 1);    int3();                                   /* int3 */
            ii(0x91ff, 1);    int3();                                   /* int3 */
            ii(0x9200, 1);    int3();                                   /* int3 */
            ii(0x9201, 1);    int3();                                   /* int3 */
            ii(0x9202, 1);    int3();                                   /* int3 */
            ii(0x9203, 1);    int3();                                   /* int3 */
        }
    }
}
