using System;
using MikhailKhalizev.Processor.x86.BinToCSharp;

namespace MikhailKhalizev.Max.Program
{
    public partial class RawProgram
    {
        [MethodInfo("13b43069-7605-42f6-a0f0-a728908bacb1")]
        public void Method_0000_9204()
        {
            ii(0x9204, 1);    int3();                                   /* int3 */
            ii(0x9205, 1);    int3();                                   /* int3 */
            ii(0x9206, 1);    int3();                                   /* int3 */
            ii(0x9207, 1);    int3();                                   /* int3 */
            ii(0x9208, 1);    int3();                                   /* int3 */
            ii(0x9209, 1);    int3();                                   /* int3 */
            ii(0x920a, 1);    int3();                                   /* int3 */
            ii(0x920b, 1);    int3();                                   /* int3 */
            ii(0x920c, 1);    int3();                                   /* int3 */
            ii(0x920d, 1);    int3();                                   /* int3 */
            ii(0x920e, 1);    int3();                                   /* int3 */
            ii(0x920f, 1);    int3();                                   /* int3 */
            ii(0x9210, 1);    int3();                                   /* int3 */
            ii(0x9211, 1);    int3();                                   /* int3 */
            ii(0x9212, 1);    int3();                                   /* int3 */
            ii(0x9213, 1);    int3();                                   /* int3 */
            ii(0x9214, 1);    int3();                                   /* int3 */
            ii(0x9215, 1);    int3();                                   /* int3 */
            ii(0x9216, 1);    int3();                                   /* int3 */
            ii(0x9217, 1);    int3();                                   /* int3 */
            ii(0x9218, 1);    int3();                                   /* int3 */
            ii(0x9219, 1);    int3();                                   /* int3 */
            ii(0x921a, 1);    int3();                                   /* int3 */
            ii(0x921b, 1);    int3();                                   /* int3 */
            ii(0x921c, 1);    int3();                                   /* int3 */
            ii(0x921d, 1);    int3();                                   /* int3 */
            ii(0x921e, 1);    int3();                                   /* int3 */
            ii(0x921f, 1);    int3();                                   /* int3 */
            ii(0x9220, 1);    int3();                                   /* int3 */
            ii(0x9221, 1);    int3();                                   /* int3 */
            ii(0x9222, 1);    int3();                                   /* int3 */
            ii(0x9223, 1);    int3();                                   /* int3 */
            ii(0x9224, 1);    int3();                                   /* int3 */
            ii(0x9225, 1);    int3();                                   /* int3 */
            ii(0x9226, 1);    int3();                                   /* int3 */
            ii(0x9227, 1);    int3();                                   /* int3 */
            ii(0x9228, 1);    int3();                                   /* int3 */
            ii(0x9229, 1);    int3();                                   /* int3 */
            ii(0x922a, 1);    int3();                                   /* int3 */
            ii(0x922b, 1);    int3();                                   /* int3 */
            ii(0x922c, 1);    int3();                                   /* int3 */
            ii(0x922d, 1);    int3();                                   /* int3 */
            ii(0x922e, 1);    int3();                                   /* int3 */
            ii(0x922f, 1);    int3();                                   /* int3 */
            ii(0x9230, 1);    int3();                                   /* int3 */
            ii(0x9231, 1);    int3();                                   /* int3 */
            ii(0x9232, 1);    int3();                                   /* int3 */
            ii(0x9233, 1);    int3();                                   /* int3 */
            ii(0x9234, 1);    int3();                                   /* int3 */
            ii(0x9235, 1);    int3();                                   /* int3 */
            ii(0x9236, 1);    int3();                                   /* int3 */
            ii(0x9237, 1);    int3();                                   /* int3 */
            ii(0x9238, 1);    int3();                                   /* int3 */
            ii(0x9239, 1);    int3();                                   /* int3 */
            ii(0x923a, 1);    int3();                                   /* int3 */
            ii(0x923b, 1);    int3();                                   /* int3 */
            ii(0x923c, 1);    int3();                                   /* int3 */
            ii(0x923d, 1);    int3();                                   /* int3 */
            ii(0x923e, 1);    int3();                                   /* int3 */
            ii(0x923f, 1);    int3();                                   /* int3 */
            ii(0x9240, 1);    int3();                                   /* int3 */
            ii(0x9241, 1);    int3();                                   /* int3 */
            ii(0x9242, 1);    int3();                                   /* int3 */
            ii(0x9243, 1);    int3();                                   /* int3 */
            ii(0x9244, 1);    int3();                                   /* int3 */
            ii(0x9245, 1);    int3();                                   /* int3 */
            ii(0x9246, 1);    int3();                                   /* int3 */
            ii(0x9247, 1);    int3();                                   /* int3 */
            ii(0x9248, 1);    int3();                                   /* int3 */
            ii(0x9249, 1);    int3();                                   /* int3 */
            ii(0x924a, 1);    int3();                                   /* int3 */
            ii(0x924b, 1);    int3();                                   /* int3 */
            ii(0x924c, 1);    int3();                                   /* int3 */
            ii(0x924d, 1);    int3();                                   /* int3 */
            ii(0x924e, 1);    int3();                                   /* int3 */
            ii(0x924f, 1);    int3();                                   /* int3 */
            ii(0x9250, 1);    int3();                                   /* int3 */
            ii(0x9251, 1);    int3();                                   /* int3 */
            ii(0x9252, 1);    int3();                                   /* int3 */
            ii(0x9253, 1);    int3();                                   /* int3 */
            ii(0x9254, 1);    int3();                                   /* int3 */
            ii(0x9255, 1);    int3();                                   /* int3 */
            ii(0x9256, 1);    int3();                                   /* int3 */
            ii(0x9257, 1);    int3();                                   /* int3 */
            ii(0x9258, 1);    int3();                                   /* int3 */
            ii(0x9259, 1);    int3();                                   /* int3 */
            ii(0x925a, 1);    int3();                                   /* int3 */
            ii(0x925b, 1);    int3();                                   /* int3 */
            ii(0x925c, 1);    int3();                                   /* int3 */
            ii(0x925d, 1);    int3();                                   /* int3 */
            ii(0x925e, 1);    int3();                                   /* int3 */
            ii(0x925f, 1);    int3();                                   /* int3 */
            ii(0x9260, 1);    int3();                                   /* int3 */
            ii(0x9261, 1);    int3();                                   /* int3 */
            ii(0x9262, 1);    int3();                                   /* int3 */
            ii(0x9263, 1);    int3();                                   /* int3 */
            ii(0x9264, 1);    int3();                                   /* int3 */
            ii(0x9265, 1);    int3();                                   /* int3 */
            ii(0x9266, 1);    int3();                                   /* int3 */
            ii(0x9267, 1);    int3();                                   /* int3 */
            ii(0x9268, 1);    int3();                                   /* int3 */
            ii(0x9269, 1);    int3();                                   /* int3 */
            ii(0x926a, 1);    int3();                                   /* int3 */
            ii(0x926b, 1);    int3();                                   /* int3 */
            ii(0x926c, 1);    int3();                                   /* int3 */
            ii(0x926d, 1);    int3();                                   /* int3 */
            ii(0x926e, 1);    int3();                                   /* int3 */
            ii(0x926f, 1);    int3();                                   /* int3 */
            ii(0x9270, 1);    int3();                                   /* int3 */
            ii(0x9271, 1);    int3();                                   /* int3 */
            ii(0x9272, 1);    int3();                                   /* int3 */
            ii(0x9273, 1);    int3();                                   /* int3 */
            ii(0x9274, 1);    int3();                                   /* int3 */
            ii(0x9275, 1);    int3();                                   /* int3 */
            ii(0x9276, 1);    int3();                                   /* int3 */
            ii(0x9277, 1);    int3();                                   /* int3 */
            ii(0x9278, 1);    int3();                                   /* int3 */
            ii(0x9279, 1);    int3();                                   /* int3 */
            ii(0x927a, 1);    int3();                                   /* int3 */
            ii(0x927b, 1);    int3();                                   /* int3 */
            ii(0x927c, 1);    int3();                                   /* int3 */
            ii(0x927d, 1);    int3();                                   /* int3 */
            ii(0x927e, 1);    int3();                                   /* int3 */
            ii(0x927f, 1);    int3();                                   /* int3 */
            ii(0x9280, 1);    int3();                                   /* int3 */
            ii(0x9281, 1);    int3();                                   /* int3 */
            ii(0x9282, 1);    int3();                                   /* int3 */
            ii(0x9283, 1);    int3();                                   /* int3 */
            ii(0x9284, 1);    int3();                                   /* int3 */
            ii(0x9285, 1);    int3();                                   /* int3 */
            ii(0x9286, 1);    int3();                                   /* int3 */
            ii(0x9287, 1);    int3();                                   /* int3 */
            ii(0x9288, 1);    int3();                                   /* int3 */
            ii(0x9289, 1);    int3();                                   /* int3 */
            ii(0x928a, 1);    int3();                                   /* int3 */
            ii(0x928b, 1);    int3();                                   /* int3 */
            ii(0x928c, 1);    int3();                                   /* int3 */
            ii(0x928d, 1);    int3();                                   /* int3 */
            ii(0x928e, 1);    int3();                                   /* int3 */
            ii(0x928f, 1);    int3();                                   /* int3 */
            ii(0x9290, 1);    int3();                                   /* int3 */
            ii(0x9291, 1);    int3();                                   /* int3 */
            ii(0x9292, 1);    int3();                                   /* int3 */
            ii(0x9293, 1);    int3();                                   /* int3 */
            ii(0x9294, 1);    int3();                                   /* int3 */
            ii(0x9295, 1);    int3();                                   /* int3 */
            ii(0x9296, 1);    int3();                                   /* int3 */
            ii(0x9297, 1);    int3();                                   /* int3 */
            ii(0x9298, 1);    int3();                                   /* int3 */
            ii(0x9299, 1);    int3();                                   /* int3 */
            ii(0x929a, 1);    int3();                                   /* int3 */
            ii(0x929b, 1);    int3();                                   /* int3 */
            ii(0x929c, 1);    int3();                                   /* int3 */
            ii(0x929d, 1);    int3();                                   /* int3 */
            ii(0x929e, 1);    int3();                                   /* int3 */
            ii(0x929f, 1);    int3();                                   /* int3 */
            ii(0x92a0, 1);    int3();                                   /* int3 */
            ii(0x92a1, 1);    int3();                                   /* int3 */
            ii(0x92a2, 1);    int3();                                   /* int3 */
            ii(0x92a3, 1);    int3();                                   /* int3 */
            ii(0x92a4, 1);    int3();                                   /* int3 */
            ii(0x92a5, 1);    int3();                                   /* int3 */
            ii(0x92a6, 1);    int3();                                   /* int3 */
            ii(0x92a7, 1);    int3();                                   /* int3 */
            ii(0x92a8, 1);    int3();                                   /* int3 */
            ii(0x92a9, 1);    int3();                                   /* int3 */
            ii(0x92aa, 1);    int3();                                   /* int3 */
            ii(0x92ab, 1);    int3();                                   /* int3 */
            ii(0x92ac, 1);    int3();                                   /* int3 */
            ii(0x92ad, 1);    int3();                                   /* int3 */
            ii(0x92ae, 1);    int3();                                   /* int3 */
            ii(0x92af, 1);    int3();                                   /* int3 */
            ii(0x92b0, 1);    int3();                                   /* int3 */
            ii(0x92b1, 1);    int3();                                   /* int3 */
            ii(0x92b2, 1);    int3();                                   /* int3 */
            ii(0x92b3, 1);    int3();                                   /* int3 */
            ii(0x92b4, 1);    int3();                                   /* int3 */
            ii(0x92b5, 1);    int3();                                   /* int3 */
            ii(0x92b6, 1);    int3();                                   /* int3 */
            ii(0x92b7, 1);    int3();                                   /* int3 */
            ii(0x92b8, 1);    int3();                                   /* int3 */
            ii(0x92b9, 1);    int3();                                   /* int3 */
            ii(0x92ba, 1);    int3();                                   /* int3 */
            ii(0x92bb, 1);    int3();                                   /* int3 */
            ii(0x92bc, 1);    int3();                                   /* int3 */
            ii(0x92bd, 1);    int3();                                   /* int3 */
            ii(0x92be, 1);    int3();                                   /* int3 */
            ii(0x92bf, 1);    int3();                                   /* int3 */
            ii(0x92c0, 1);    int3();                                   /* int3 */
            ii(0x92c1, 1);    int3();                                   /* int3 */
            ii(0x92c2, 1);    int3();                                   /* int3 */
            ii(0x92c3, 1);    int3();                                   /* int3 */
            ii(0x92c4, 1);    int3();                                   /* int3 */
            ii(0x92c5, 1);    int3();                                   /* int3 */
            ii(0x92c6, 1);    int3();                                   /* int3 */
            ii(0x92c7, 1);    int3();                                   /* int3 */
            ii(0x92c8, 1);    int3();                                   /* int3 */
            ii(0x92c9, 1);    int3();                                   /* int3 */
            ii(0x92ca, 1);    int3();                                   /* int3 */
            ii(0x92cb, 1);    int3();                                   /* int3 */
            ii(0x92cc, 1);    int3();                                   /* int3 */
            ii(0x92cd, 1);    int3();                                   /* int3 */
            ii(0x92ce, 1);    int3();                                   /* int3 */
            ii(0x92cf, 1);    int3();                                   /* int3 */
            ii(0x92d0, 1);    int3();                                   /* int3 */
            ii(0x92d1, 1);    int3();                                   /* int3 */
            ii(0x92d2, 1);    int3();                                   /* int3 */
            ii(0x92d3, 1);    int3();                                   /* int3 */
            ii(0x92d4, 1);    int3();                                   /* int3 */
            ii(0x92d5, 1);    int3();                                   /* int3 */
            ii(0x92d6, 1);    int3();                                   /* int3 */
            ii(0x92d7, 1);    int3();                                   /* int3 */
            ii(0x92d8, 1);    int3();                                   /* int3 */
            ii(0x92d9, 1);    int3();                                   /* int3 */
            ii(0x92da, 1);    int3();                                   /* int3 */
            ii(0x92db, 1);    int3();                                   /* int3 */
            ii(0x92dc, 1);    int3();                                   /* int3 */
            ii(0x92dd, 1);    int3();                                   /* int3 */
            ii(0x92de, 1);    int3();                                   /* int3 */
            ii(0x92df, 1);    int3();                                   /* int3 */
            ii(0x92e0, 1);    int3();                                   /* int3 */
            ii(0x92e1, 1);    int3();                                   /* int3 */
            ii(0x92e2, 1);    int3();                                   /* int3 */
            ii(0x92e3, 1);    int3();                                   /* int3 */
            ii(0x92e4, 1);    int3();                                   /* int3 */
            ii(0x92e5, 1);    int3();                                   /* int3 */
            ii(0x92e6, 1);    int3();                                   /* int3 */
            ii(0x92e7, 1);    int3();                                   /* int3 */
            ii(0x92e8, 1);    int3();                                   /* int3 */
            ii(0x92e9, 1);    int3();                                   /* int3 */
            ii(0x92ea, 1);    int3();                                   /* int3 */
            ii(0x92eb, 1);    int3();                                   /* int3 */
            ii(0x92ec, 1);    int3();                                   /* int3 */
            ii(0x92ed, 1);    int3();                                   /* int3 */
            ii(0x92ee, 1);    int3();                                   /* int3 */
            ii(0x92ef, 1);    int3();                                   /* int3 */
            ii(0x92f0, 1);    int3();                                   /* int3 */
            ii(0x92f1, 1);    int3();                                   /* int3 */
            ii(0x92f2, 1);    int3();                                   /* int3 */
            ii(0x92f3, 1);    int3();                                   /* int3 */
            ii(0x92f4, 1);    int3();                                   /* int3 */
            ii(0x92f5, 1);    int3();                                   /* int3 */
            ii(0x92f6, 1);    int3();                                   /* int3 */
            ii(0x92f7, 1);    int3();                                   /* int3 */
            ii(0x92f8, 1);    int3();                                   /* int3 */
            ii(0x92f9, 1);    int3();                                   /* int3 */
            ii(0x92fa, 1);    int3();                                   /* int3 */
            ii(0x92fb, 1);    int3();                                   /* int3 */
            ii(0x92fc, 1);    int3();                                   /* int3 */
            ii(0x92fd, 1);    int3();                                   /* int3 */
            ii(0x92fe, 1);    int3();                                   /* int3 */
            ii(0x92ff, 1);    int3();                                   /* int3 */
            ii(0x9300, 1);    int3();                                   /* int3 */
            ii(0x9301, 1);    int3();                                   /* int3 */
            ii(0x9302, 1);    int3();                                   /* int3 */
            ii(0x9303, 1);    int3();                                   /* int3 */
            ii(0x9304, 1);    int3();                                   /* int3 */
            ii(0x9305, 1);    int3();                                   /* int3 */
            ii(0x9306, 1);    int3();                                   /* int3 */
            ii(0x9307, 1);    int3();                                   /* int3 */
            ii(0x9308, 1);    int3();                                   /* int3 */
            ii(0x9309, 1);    int3();                                   /* int3 */
            ii(0x930a, 1);    int3();                                   /* int3 */
            ii(0x930b, 1);    int3();                                   /* int3 */
            ii(0x930c, 1);    int3();                                   /* int3 */
            ii(0x930d, 1);    int3();                                   /* int3 */
            ii(0x930e, 1);    int3();                                   /* int3 */
            ii(0x930f, 1);    int3();                                   /* int3 */
            ii(0x9310, 1);    int3();                                   /* int3 */
            ii(0x9311, 1);    int3();                                   /* int3 */
            ii(0x9312, 1);    int3();                                   /* int3 */
            ii(0x9313, 1);    int3();                                   /* int3 */
            ii(0x9314, 1);    int3();                                   /* int3 */
            ii(0x9315, 1);    int3();                                   /* int3 */
            ii(0x9316, 1);    int3();                                   /* int3 */
            ii(0x9317, 1);    int3();                                   /* int3 */
            ii(0x9318, 1);    int3();                                   /* int3 */
            ii(0x9319, 1);    int3();                                   /* int3 */
            ii(0x931a, 1);    int3();                                   /* int3 */
            ii(0x931b, 1);    int3();                                   /* int3 */
            ii(0x931c, 1);    int3();                                   /* int3 */
            ii(0x931d, 1);    int3();                                   /* int3 */
            ii(0x931e, 1);    int3();                                   /* int3 */
            ii(0x931f, 1);    int3();                                   /* int3 */
            ii(0x9320, 1);    int3();                                   /* int3 */
            ii(0x9321, 1);    int3();                                   /* int3 */
            ii(0x9322, 1);    int3();                                   /* int3 */
            ii(0x9323, 1);    int3();                                   /* int3 */
            ii(0x9324, 1);    int3();                                   /* int3 */
            ii(0x9325, 1);    int3();                                   /* int3 */
            ii(0x9326, 1);    int3();                                   /* int3 */
            ii(0x9327, 1);    int3();                                   /* int3 */
            ii(0x9328, 1);    int3();                                   /* int3 */
            ii(0x9329, 1);    int3();                                   /* int3 */
            ii(0x932a, 1);    int3();                                   /* int3 */
            ii(0x932b, 1);    int3();                                   /* int3 */
            ii(0x932c, 1);    int3();                                   /* int3 */
            ii(0x932d, 1);    int3();                                   /* int3 */
            ii(0x932e, 1);    int3();                                   /* int3 */
            ii(0x932f, 1);    int3();                                   /* int3 */
            ii(0x9330, 1);    int3();                                   /* int3 */
            ii(0x9331, 1);    int3();                                   /* int3 */
            ii(0x9332, 1);    int3();                                   /* int3 */
            ii(0x9333, 1);    int3();                                   /* int3 */
            ii(0x9334, 1);    int3();                                   /* int3 */
            ii(0x9335, 1);    int3();                                   /* int3 */
            ii(0x9336, 1);    int3();                                   /* int3 */
            ii(0x9337, 1);    int3();                                   /* int3 */
            ii(0x9338, 1);    int3();                                   /* int3 */
            ii(0x9339, 1);    int3();                                   /* int3 */
            ii(0x933a, 1);    int3();                                   /* int3 */
            ii(0x933b, 1);    int3();                                   /* int3 */
            ii(0x933c, 1);    int3();                                   /* int3 */
            ii(0x933d, 1);    int3();                                   /* int3 */
            ii(0x933e, 1);    int3();                                   /* int3 */
            ii(0x933f, 1);    int3();                                   /* int3 */
            ii(0x9340, 1);    int3();                                   /* int3 */
            ii(0x9341, 1);    int3();                                   /* int3 */
            ii(0x9342, 1);    int3();                                   /* int3 */
            ii(0x9343, 1);    int3();                                   /* int3 */
            ii(0x9344, 1);    int3();                                   /* int3 */
            ii(0x9345, 1);    int3();                                   /* int3 */
            ii(0x9346, 1);    int3();                                   /* int3 */
            ii(0x9347, 1);    int3();                                   /* int3 */
            ii(0x9348, 1);    int3();                                   /* int3 */
            ii(0x9349, 1);    int3();                                   /* int3 */
            ii(0x934a, 1);    int3();                                   /* int3 */
            ii(0x934b, 1);    int3();                                   /* int3 */
            ii(0x934c, 1);    int3();                                   /* int3 */
            ii(0x934d, 1);    int3();                                   /* int3 */
            ii(0x934e, 1);    int3();                                   /* int3 */
            ii(0x934f, 1);    int3();                                   /* int3 */
            ii(0x9350, 1);    int3();                                   /* int3 */
            ii(0x9351, 1);    int3();                                   /* int3 */
            ii(0x9352, 1);    int3();                                   /* int3 */
            ii(0x9353, 1);    int3();                                   /* int3 */
            ii(0x9354, 1);    int3();                                   /* int3 */
            ii(0x9355, 1);    int3();                                   /* int3 */
            ii(0x9356, 1);    int3();                                   /* int3 */
            ii(0x9357, 1);    int3();                                   /* int3 */
            ii(0x9358, 1);    int3();                                   /* int3 */
            ii(0x9359, 1);    int3();                                   /* int3 */
            ii(0x935a, 1);    int3();                                   /* int3 */
            ii(0x935b, 1);    int3();                                   /* int3 */
            ii(0x935c, 1);    int3();                                   /* int3 */
            ii(0x935d, 1);    int3();                                   /* int3 */
            ii(0x935e, 1);    int3();                                   /* int3 */
            ii(0x935f, 1);    int3();                                   /* int3 */
            ii(0x9360, 1);    int3();                                   /* int3 */
            ii(0x9361, 1);    int3();                                   /* int3 */
            ii(0x9362, 1);    int3();                                   /* int3 */
            ii(0x9363, 1);    int3();                                   /* int3 */
            ii(0x9364, 1);    int3();                                   /* int3 */
            ii(0x9365, 1);    int3();                                   /* int3 */
            ii(0x9366, 1);    int3();                                   /* int3 */
            ii(0x9367, 1);    int3();                                   /* int3 */
            ii(0x9368, 1);    int3();                                   /* int3 */
            ii(0x9369, 1);    int3();                                   /* int3 */
            ii(0x936a, 1);    int3();                                   /* int3 */
            ii(0x936b, 1);    int3();                                   /* int3 */
            ii(0x936c, 1);    int3();                                   /* int3 */
            ii(0x936d, 1);    int3();                                   /* int3 */
            ii(0x936e, 1);    int3();                                   /* int3 */
            ii(0x936f, 1);    int3();                                   /* int3 */
            ii(0x9370, 1);    int3();                                   /* int3 */
            ii(0x9371, 1);    int3();                                   /* int3 */
            ii(0x9372, 1);    int3();                                   /* int3 */
            ii(0x9373, 1);    int3();                                   /* int3 */
            ii(0x9374, 1);    int3();                                   /* int3 */
            ii(0x9375, 1);    int3();                                   /* int3 */
            ii(0x9376, 1);    int3();                                   /* int3 */
            ii(0x9377, 1);    int3();                                   /* int3 */
            ii(0x9378, 1);    int3();                                   /* int3 */
            ii(0x9379, 1);    int3();                                   /* int3 */
            ii(0x937a, 1);    int3();                                   /* int3 */
            ii(0x937b, 1);    int3();                                   /* int3 */
            ii(0x937c, 1);    int3();                                   /* int3 */
            ii(0x937d, 1);    int3();                                   /* int3 */
            ii(0x937e, 1);    int3();                                   /* int3 */
            ii(0x937f, 1);    int3();                                   /* int3 */
            ii(0x9380, 1);    int3();                                   /* int3 */
            ii(0x9381, 1);    int3();                                   /* int3 */
            ii(0x9382, 1);    int3();                                   /* int3 */
            ii(0x9383, 1);    int3();                                   /* int3 */
            ii(0x9384, 1);    int3();                                   /* int3 */
            ii(0x9385, 1);    int3();                                   /* int3 */
            ii(0x9386, 1);    int3();                                   /* int3 */
            ii(0x9387, 1);    int3();                                   /* int3 */
            ii(0x9388, 1);    int3();                                   /* int3 */
            ii(0x9389, 1);    int3();                                   /* int3 */
            ii(0x938a, 1);    int3();                                   /* int3 */
            ii(0x938b, 1);    int3();                                   /* int3 */
            ii(0x938c, 1);    int3();                                   /* int3 */
            ii(0x938d, 1);    int3();                                   /* int3 */
            ii(0x938e, 1);    int3();                                   /* int3 */
            ii(0x938f, 1);    int3();                                   /* int3 */
            ii(0x9390, 1);    int3();                                   /* int3 */
            ii(0x9391, 1);    int3();                                   /* int3 */
            ii(0x9392, 1);    int3();                                   /* int3 */
            ii(0x9393, 1);    int3();                                   /* int3 */
            ii(0x9394, 1);    int3();                                   /* int3 */
            ii(0x9395, 1);    int3();                                   /* int3 */
            ii(0x9396, 1);    int3();                                   /* int3 */
            ii(0x9397, 1);    int3();                                   /* int3 */
            ii(0x9398, 1);    int3();                                   /* int3 */
            ii(0x9399, 1);    int3();                                   /* int3 */
            ii(0x939a, 1);    int3();                                   /* int3 */
            ii(0x939b, 1);    int3();                                   /* int3 */
            ii(0x939c, 1);    int3();                                   /* int3 */
            ii(0x939d, 1);    int3();                                   /* int3 */
            ii(0x939e, 1);    int3();                                   /* int3 */
            ii(0x939f, 1);    int3();                                   /* int3 */
            ii(0x93a0, 1);    int3();                                   /* int3 */
            ii(0x93a1, 1);    int3();                                   /* int3 */
            ii(0x93a2, 1);    int3();                                   /* int3 */
            ii(0x93a3, 1);    int3();                                   /* int3 */
            ii(0x93a4, 1);    int3();                                   /* int3 */
            ii(0x93a5, 1);    int3();                                   /* int3 */
            ii(0x93a6, 1);    int3();                                   /* int3 */
            ii(0x93a7, 1);    int3();                                   /* int3 */
            ii(0x93a8, 1);    int3();                                   /* int3 */
            ii(0x93a9, 1);    int3();                                   /* int3 */
            ii(0x93aa, 1);    int3();                                   /* int3 */
            ii(0x93ab, 1);    int3();                                   /* int3 */
            ii(0x93ac, 1);    int3();                                   /* int3 */
            ii(0x93ad, 1);    int3();                                   /* int3 */
            ii(0x93ae, 1);    int3();                                   /* int3 */
            ii(0x93af, 1);    int3();                                   /* int3 */
            ii(0x93b0, 1);    int3();                                   /* int3 */
            ii(0x93b1, 1);    int3();                                   /* int3 */
            ii(0x93b2, 1);    int3();                                   /* int3 */
            ii(0x93b3, 1);    int3();                                   /* int3 */
            ii(0x93b4, 1);    int3();                                   /* int3 */
            ii(0x93b5, 1);    int3();                                   /* int3 */
            ii(0x93b6, 1);    int3();                                   /* int3 */
            ii(0x93b7, 1);    int3();                                   /* int3 */
            ii(0x93b8, 1);    int3();                                   /* int3 */
            ii(0x93b9, 1);    int3();                                   /* int3 */
            ii(0x93ba, 1);    int3();                                   /* int3 */
            ii(0x93bb, 1);    int3();                                   /* int3 */
            ii(0x93bc, 1);    int3();                                   /* int3 */
            ii(0x93bd, 1);    int3();                                   /* int3 */
            ii(0x93be, 1);    int3();                                   /* int3 */
            ii(0x93bf, 1);    int3();                                   /* int3 */
            ii(0x93c0, 1);    int3();                                   /* int3 */
            ii(0x93c1, 1);    int3();                                   /* int3 */
            ii(0x93c2, 1);    int3();                                   /* int3 */
            ii(0x93c3, 1);    int3();                                   /* int3 */
            ii(0x93c4, 1);    int3();                                   /* int3 */
            ii(0x93c5, 1);    int3();                                   /* int3 */
            ii(0x93c6, 1);    int3();                                   /* int3 */
            ii(0x93c7, 1);    int3();                                   /* int3 */
            ii(0x93c8, 1);    int3();                                   /* int3 */
            ii(0x93c9, 1);    int3();                                   /* int3 */
            ii(0x93ca, 1);    int3();                                   /* int3 */
            ii(0x93cb, 1);    int3();                                   /* int3 */
            ii(0x93cc, 1);    int3();                                   /* int3 */
            ii(0x93cd, 1);    int3();                                   /* int3 */
            ii(0x93ce, 1);    int3();                                   /* int3 */
            ii(0x93cf, 1);    int3();                                   /* int3 */
            ii(0x93d0, 1);    int3();                                   /* int3 */
            ii(0x93d1, 1);    int3();                                   /* int3 */
            ii(0x93d2, 1);    int3();                                   /* int3 */
            ii(0x93d3, 1);    int3();                                   /* int3 */
            ii(0x93d4, 1);    int3();                                   /* int3 */
            ii(0x93d5, 1);    int3();                                   /* int3 */
            ii(0x93d6, 1);    int3();                                   /* int3 */
            ii(0x93d7, 1);    int3();                                   /* int3 */
            ii(0x93d8, 1);    int3();                                   /* int3 */
            ii(0x93d9, 1);    int3();                                   /* int3 */
            ii(0x93da, 1);    int3();                                   /* int3 */
            ii(0x93db, 1);    int3();                                   /* int3 */
            ii(0x93dc, 1);    int3();                                   /* int3 */
            ii(0x93dd, 1);    int3();                                   /* int3 */
            ii(0x93de, 1);    int3();                                   /* int3 */
            ii(0x93df, 1);    int3();                                   /* int3 */
            ii(0x93e0, 1);    int3();                                   /* int3 */
            ii(0x93e1, 1);    int3();                                   /* int3 */
            ii(0x93e2, 1);    int3();                                   /* int3 */
            ii(0x93e3, 1);    int3();                                   /* int3 */
            ii(0x93e4, 1);    int3();                                   /* int3 */
            ii(0x93e5, 1);    int3();                                   /* int3 */
            ii(0x93e6, 1);    int3();                                   /* int3 */
            ii(0x93e7, 1);    int3();                                   /* int3 */
            ii(0x93e8, 1);    int3();                                   /* int3 */
            ii(0x93e9, 1);    int3();                                   /* int3 */
            ii(0x93ea, 1);    int3();                                   /* int3 */
            ii(0x93eb, 1);    int3();                                   /* int3 */
            ii(0x93ec, 1);    int3();                                   /* int3 */
            ii(0x93ed, 1);    int3();                                   /* int3 */
            ii(0x93ee, 1);    int3();                                   /* int3 */
            ii(0x93ef, 1);    int3();                                   /* int3 */
            ii(0x93f0, 1);    int3();                                   /* int3 */
            ii(0x93f1, 1);    int3();                                   /* int3 */
            ii(0x93f2, 1);    int3();                                   /* int3 */
            ii(0x93f3, 1);    int3();                                   /* int3 */
            ii(0x93f4, 1);    int3();                                   /* int3 */
            ii(0x93f5, 1);    int3();                                   /* int3 */
            ii(0x93f6, 1);    int3();                                   /* int3 */
            ii(0x93f7, 1);    int3();                                   /* int3 */
            ii(0x93f8, 1);    int3();                                   /* int3 */
            ii(0x93f9, 1);    int3();                                   /* int3 */
            ii(0x93fa, 1);    int3();                                   /* int3 */
            ii(0x93fb, 1);    int3();                                   /* int3 */
            ii(0x93fc, 1);    int3();                                   /* int3 */
            ii(0x93fd, 1);    int3();                                   /* int3 */
            ii(0x93fe, 1);    int3();                                   /* int3 */
            ii(0x93ff, 1);    int3();                                   /* int3 */
            ii(0x9400, 1);    int3();                                   /* int3 */
            ii(0x9401, 1);    int3();                                   /* int3 */
            ii(0x9402, 1);    int3();                                   /* int3 */
            ii(0x9403, 1);    int3();                                   /* int3 */
            ii(0x9404, 1);    int3();                                   /* int3 */
            ii(0x9405, 1);    int3();                                   /* int3 */
            ii(0x9406, 1);    int3();                                   /* int3 */
            ii(0x9407, 1);    int3();                                   /* int3 */
            ii(0x9408, 1);    int3();                                   /* int3 */
            ii(0x9409, 1);    int3();                                   /* int3 */
            ii(0x940a, 1);    int3();                                   /* int3 */
            ii(0x940b, 1);    int3();                                   /* int3 */
            ii(0x940c, 1);    int3();                                   /* int3 */
            ii(0x940d, 1);    int3();                                   /* int3 */
            ii(0x940e, 1);    int3();                                   /* int3 */
            ii(0x940f, 1);    int3();                                   /* int3 */
            ii(0x9410, 1);    int3();                                   /* int3 */
            ii(0x9411, 1);    int3();                                   /* int3 */
            ii(0x9412, 1);    int3();                                   /* int3 */
            ii(0x9413, 1);    int3();                                   /* int3 */
            ii(0x9414, 1);    int3();                                   /* int3 */
            ii(0x9415, 1);    int3();                                   /* int3 */
            ii(0x9416, 1);    int3();                                   /* int3 */
            ii(0x9417, 1);    int3();                                   /* int3 */
            ii(0x9418, 1);    int3();                                   /* int3 */
            ii(0x9419, 1);    int3();                                   /* int3 */
            ii(0x941a, 1);    int3();                                   /* int3 */
            ii(0x941b, 1);    int3();                                   /* int3 */
            ii(0x941c, 1);    int3();                                   /* int3 */
            ii(0x941d, 1);    int3();                                   /* int3 */
            ii(0x941e, 1);    int3();                                   /* int3 */
            ii(0x941f, 1);    int3();                                   /* int3 */
            ii(0x9420, 1);    int3();                                   /* int3 */
            ii(0x9421, 1);    int3();                                   /* int3 */
            ii(0x9422, 1);    int3();                                   /* int3 */
            ii(0x9423, 1);    int3();                                   /* int3 */
            ii(0x9424, 1);    int3();                                   /* int3 */
            ii(0x9425, 1);    int3();                                   /* int3 */
            ii(0x9426, 1);    int3();                                   /* int3 */
            ii(0x9427, 1);    int3();                                   /* int3 */
            ii(0x9428, 1);    int3();                                   /* int3 */
            ii(0x9429, 1);    int3();                                   /* int3 */
            ii(0x942a, 1);    int3();                                   /* int3 */
            ii(0x942b, 1);    int3();                                   /* int3 */
            ii(0x942c, 1);    int3();                                   /* int3 */
            ii(0x942d, 1);    int3();                                   /* int3 */
            ii(0x942e, 1);    int3();                                   /* int3 */
            ii(0x942f, 1);    int3();                                   /* int3 */
            ii(0x9430, 1);    int3();                                   /* int3 */
            ii(0x9431, 1);    int3();                                   /* int3 */
            ii(0x9432, 1);    int3();                                   /* int3 */
            ii(0x9433, 1);    int3();                                   /* int3 */
            ii(0x9434, 1);    int3();                                   /* int3 */
            ii(0x9435, 1);    int3();                                   /* int3 */
            ii(0x9436, 1);    int3();                                   /* int3 */
            ii(0x9437, 1);    int3();                                   /* int3 */
            ii(0x9438, 1);    int3();                                   /* int3 */
            ii(0x9439, 1);    int3();                                   /* int3 */
            ii(0x943a, 1);    int3();                                   /* int3 */
            ii(0x943b, 1);    int3();                                   /* int3 */
            ii(0x943c, 1);    int3();                                   /* int3 */
            ii(0x943d, 1);    int3();                                   /* int3 */
            ii(0x943e, 1);    int3();                                   /* int3 */
            ii(0x943f, 1);    int3();                                   /* int3 */
            ii(0x9440, 1);    int3();                                   /* int3 */
            ii(0x9441, 1);    int3();                                   /* int3 */
            ii(0x9442, 1);    int3();                                   /* int3 */
            ii(0x9443, 1);    int3();                                   /* int3 */
            ii(0x9444, 1);    int3();                                   /* int3 */
            ii(0x9445, 1);    int3();                                   /* int3 */
            ii(0x9446, 1);    int3();                                   /* int3 */
            ii(0x9447, 1);    int3();                                   /* int3 */
            ii(0x9448, 1);    int3();                                   /* int3 */
            ii(0x9449, 1);    int3();                                   /* int3 */
            ii(0x944a, 1);    int3();                                   /* int3 */
            ii(0x944b, 1);    int3();                                   /* int3 */
            ii(0x944c, 1);    int3();                                   /* int3 */
            ii(0x944d, 1);    int3();                                   /* int3 */
            ii(0x944e, 1);    int3();                                   /* int3 */
            ii(0x944f, 1);    int3();                                   /* int3 */
            ii(0x9450, 1);    int3();                                   /* int3 */
            ii(0x9451, 1);    int3();                                   /* int3 */
            ii(0x9452, 1);    int3();                                   /* int3 */
            ii(0x9453, 1);    int3();                                   /* int3 */
            ii(0x9454, 1);    int3();                                   /* int3 */
            ii(0x9455, 1);    int3();                                   /* int3 */
            ii(0x9456, 1);    int3();                                   /* int3 */
            ii(0x9457, 1);    int3();                                   /* int3 */
            ii(0x9458, 1);    int3();                                   /* int3 */
            ii(0x9459, 1);    int3();                                   /* int3 */
            ii(0x945a, 1);    int3();                                   /* int3 */
            ii(0x945b, 1);    int3();                                   /* int3 */
            ii(0x945c, 1);    int3();                                   /* int3 */
            ii(0x945d, 1);    int3();                                   /* int3 */
            ii(0x945e, 1);    int3();                                   /* int3 */
            ii(0x945f, 1);    int3();                                   /* int3 */
            ii(0x9460, 1);    int3();                                   /* int3 */
            ii(0x9461, 1);    int3();                                   /* int3 */
            ii(0x9462, 1);    int3();                                   /* int3 */
            ii(0x9463, 1);    int3();                                   /* int3 */
            ii(0x9464, 1);    int3();                                   /* int3 */
            ii(0x9465, 1);    int3();                                   /* int3 */
            ii(0x9466, 1);    int3();                                   /* int3 */
            ii(0x9467, 1);    int3();                                   /* int3 */
            ii(0x9468, 1);    int3();                                   /* int3 */
            ii(0x9469, 1);    int3();                                   /* int3 */
            ii(0x946a, 1);    int3();                                   /* int3 */
            ii(0x946b, 1);    int3();                                   /* int3 */
            ii(0x946c, 1);    int3();                                   /* int3 */
            ii(0x946d, 1);    int3();                                   /* int3 */
            ii(0x946e, 1);    int3();                                   /* int3 */
            ii(0x946f, 1);    int3();                                   /* int3 */
            ii(0x9470, 1);    int3();                                   /* int3 */
            ii(0x9471, 1);    int3();                                   /* int3 */
            ii(0x9472, 1);    int3();                                   /* int3 */
            ii(0x9473, 1);    int3();                                   /* int3 */
            ii(0x9474, 1);    int3();                                   /* int3 */
            ii(0x9475, 1);    int3();                                   /* int3 */
            ii(0x9476, 1);    int3();                                   /* int3 */
            ii(0x9477, 1);    int3();                                   /* int3 */
            ii(0x9478, 1);    int3();                                   /* int3 */
            ii(0x9479, 1);    int3();                                   /* int3 */
            ii(0x947a, 1);    int3();                                   /* int3 */
            ii(0x947b, 1);    int3();                                   /* int3 */
            ii(0x947c, 1);    int3();                                   /* int3 */
            ii(0x947d, 1);    int3();                                   /* int3 */
            ii(0x947e, 1);    int3();                                   /* int3 */
            ii(0x947f, 1);    int3();                                   /* int3 */
            ii(0x9480, 1);    int3();                                   /* int3 */
            ii(0x9481, 1);    int3();                                   /* int3 */
            ii(0x9482, 1);    int3();                                   /* int3 */
            ii(0x9483, 1);    int3();                                   /* int3 */
            ii(0x9484, 1);    int3();                                   /* int3 */
            ii(0x9485, 1);    int3();                                   /* int3 */
            ii(0x9486, 1);    int3();                                   /* int3 */
            ii(0x9487, 1);    int3();                                   /* int3 */
            ii(0x9488, 1);    int3();                                   /* int3 */
            ii(0x9489, 1);    int3();                                   /* int3 */
            ii(0x948a, 1);    int3();                                   /* int3 */
            ii(0x948b, 1);    int3();                                   /* int3 */
            ii(0x948c, 1);    int3();                                   /* int3 */
            ii(0x948d, 1);    int3();                                   /* int3 */
            ii(0x948e, 1);    int3();                                   /* int3 */
            ii(0x948f, 1);    int3();                                   /* int3 */
            ii(0x9490, 1);    int3();                                   /* int3 */
            ii(0x9491, 1);    int3();                                   /* int3 */
            ii(0x9492, 1);    int3();                                   /* int3 */
            ii(0x9493, 1);    int3();                                   /* int3 */
            ii(0x9494, 1);    int3();                                   /* int3 */
            ii(0x9495, 1);    int3();                                   /* int3 */
            ii(0x9496, 1);    int3();                                   /* int3 */
            ii(0x9497, 1);    int3();                                   /* int3 */
            ii(0x9498, 1);    int3();                                   /* int3 */
            ii(0x9499, 1);    int3();                                   /* int3 */
            ii(0x949a, 1);    int3();                                   /* int3 */
            ii(0x949b, 1);    int3();                                   /* int3 */
            ii(0x949c, 1);    int3();                                   /* int3 */
            ii(0x949d, 1);    int3();                                   /* int3 */
            ii(0x949e, 1);    int3();                                   /* int3 */
            ii(0x949f, 1);    int3();                                   /* int3 */
            ii(0x94a0, 1);    int3();                                   /* int3 */
            ii(0x94a1, 1);    int3();                                   /* int3 */
            ii(0x94a2, 1);    int3();                                   /* int3 */
            ii(0x94a3, 1);    int3();                                   /* int3 */
            ii(0x94a4, 1);    int3();                                   /* int3 */
            ii(0x94a5, 1);    int3();                                   /* int3 */
            ii(0x94a6, 1);    int3();                                   /* int3 */
            ii(0x94a7, 1);    int3();                                   /* int3 */
            ii(0x94a8, 1);    int3();                                   /* int3 */
            ii(0x94a9, 1);    int3();                                   /* int3 */
            ii(0x94aa, 1);    int3();                                   /* int3 */
            ii(0x94ab, 1);    int3();                                   /* int3 */
            ii(0x94ac, 1);    int3();                                   /* int3 */
            ii(0x94ad, 1);    int3();                                   /* int3 */
            ii(0x94ae, 1);    int3();                                   /* int3 */
            ii(0x94af, 1);    int3();                                   /* int3 */
            ii(0x94b0, 1);    int3();                                   /* int3 */
            ii(0x94b1, 1);    int3();                                   /* int3 */
            ii(0x94b2, 1);    int3();                                   /* int3 */
            ii(0x94b3, 1);    int3();                                   /* int3 */
            ii(0x94b4, 1);    int3();                                   /* int3 */
            ii(0x94b5, 1);    int3();                                   /* int3 */
            ii(0x94b6, 1);    int3();                                   /* int3 */
            ii(0x94b7, 1);    int3();                                   /* int3 */
            ii(0x94b8, 1);    int3();                                   /* int3 */
            ii(0x94b9, 1);    int3();                                   /* int3 */
            ii(0x94ba, 1);    int3();                                   /* int3 */
            ii(0x94bb, 1);    int3();                                   /* int3 */
            ii(0x94bc, 1);    int3();                                   /* int3 */
            ii(0x94bd, 1);    int3();                                   /* int3 */
            ii(0x94be, 1);    int3();                                   /* int3 */
            ii(0x94bf, 1);    int3();                                   /* int3 */
            ii(0x94c0, 1);    int3();                                   /* int3 */
            ii(0x94c1, 1);    int3();                                   /* int3 */
            ii(0x94c2, 1);    int3();                                   /* int3 */
            ii(0x94c3, 1);    int3();                                   /* int3 */
            ii(0x94c4, 1);    int3();                                   /* int3 */
            ii(0x94c5, 1);    int3();                                   /* int3 */
            ii(0x94c6, 1);    int3();                                   /* int3 */
            ii(0x94c7, 1);    int3();                                   /* int3 */
            ii(0x94c8, 1);    int3();                                   /* int3 */
            ii(0x94c9, 1);    int3();                                   /* int3 */
            ii(0x94ca, 1);    int3();                                   /* int3 */
            ii(0x94cb, 1);    int3();                                   /* int3 */
            ii(0x94cc, 1);    int3();                                   /* int3 */
            ii(0x94cd, 1);    int3();                                   /* int3 */
            ii(0x94ce, 1);    int3();                                   /* int3 */
            ii(0x94cf, 1);    int3();                                   /* int3 */
            ii(0x94d0, 1);    int3();                                   /* int3 */
            ii(0x94d1, 1);    int3();                                   /* int3 */
            ii(0x94d2, 1);    int3();                                   /* int3 */
            ii(0x94d3, 1);    int3();                                   /* int3 */
            ii(0x94d4, 1);    int3();                                   /* int3 */
            ii(0x94d5, 1);    int3();                                   /* int3 */
            ii(0x94d6, 1);    int3();                                   /* int3 */
            ii(0x94d7, 1);    int3();                                   /* int3 */
            ii(0x94d8, 1);    int3();                                   /* int3 */
            ii(0x94d9, 1);    int3();                                   /* int3 */
            ii(0x94da, 1);    int3();                                   /* int3 */
            ii(0x94db, 1);    int3();                                   /* int3 */
            ii(0x94dc, 1);    int3();                                   /* int3 */
            ii(0x94dd, 1);    int3();                                   /* int3 */
            ii(0x94de, 1);    int3();                                   /* int3 */
            ii(0x94df, 1);    int3();                                   /* int3 */
            ii(0x94e0, 1);    int3();                                   /* int3 */
            ii(0x94e1, 1);    int3();                                   /* int3 */
            ii(0x94e2, 1);    int3();                                   /* int3 */
            ii(0x94e3, 1);    int3();                                   /* int3 */
            ii(0x94e4, 1);    int3();                                   /* int3 */
            ii(0x94e5, 1);    int3();                                   /* int3 */
            ii(0x94e6, 1);    int3();                                   /* int3 */
            ii(0x94e7, 1);    int3();                                   /* int3 */
            ii(0x94e8, 1);    int3();                                   /* int3 */
            ii(0x94e9, 1);    int3();                                   /* int3 */
            ii(0x94ea, 1);    int3();                                   /* int3 */
            ii(0x94eb, 1);    int3();                                   /* int3 */
            ii(0x94ec, 1);    int3();                                   /* int3 */
            ii(0x94ed, 1);    int3();                                   /* int3 */
            ii(0x94ee, 1);    int3();                                   /* int3 */
            ii(0x94ef, 1);    int3();                                   /* int3 */
            ii(0x94f0, 1);    int3();                                   /* int3 */
            ii(0x94f1, 1);    int3();                                   /* int3 */
            ii(0x94f2, 1);    int3();                                   /* int3 */
            ii(0x94f3, 1);    int3();                                   /* int3 */
            ii(0x94f4, 1);    int3();                                   /* int3 */
            ii(0x94f5, 1);    int3();                                   /* int3 */
            ii(0x94f6, 1);    int3();                                   /* int3 */
            ii(0x94f7, 1);    int3();                                   /* int3 */
            ii(0x94f8, 1);    int3();                                   /* int3 */
            ii(0x94f9, 1);    int3();                                   /* int3 */
            ii(0x94fa, 1);    int3();                                   /* int3 */
            ii(0x94fb, 1);    int3();                                   /* int3 */
            ii(0x94fc, 1);    int3();                                   /* int3 */
            ii(0x94fd, 1);    int3();                                   /* int3 */
            ii(0x94fe, 1);    int3();                                   /* int3 */
            ii(0x94ff, 1);    int3();                                   /* int3 */
            ii(0x9500, 1);    int3();                                   /* int3 */
            ii(0x9501, 1);    int3();                                   /* int3 */
            ii(0x9502, 1);    int3();                                   /* int3 */
            ii(0x9503, 1);    int3();                                   /* int3 */
            ii(0x9504, 1);    int3();                                   /* int3 */
            ii(0x9505, 1);    int3();                                   /* int3 */
            ii(0x9506, 1);    int3();                                   /* int3 */
            ii(0x9507, 1);    int3();                                   /* int3 */
            ii(0x9508, 1);    int3();                                   /* int3 */
            ii(0x9509, 1);    int3();                                   /* int3 */
            ii(0x950a, 1);    int3();                                   /* int3 */
            ii(0x950b, 1);    int3();                                   /* int3 */
            ii(0x950c, 1);    int3();                                   /* int3 */
            ii(0x950d, 1);    int3();                                   /* int3 */
            ii(0x950e, 1);    int3();                                   /* int3 */
            ii(0x950f, 1);    int3();                                   /* int3 */
            ii(0x9510, 1);    int3();                                   /* int3 */
            ii(0x9511, 1);    int3();                                   /* int3 */
            ii(0x9512, 1);    int3();                                   /* int3 */
            ii(0x9513, 1);    int3();                                   /* int3 */
            ii(0x9514, 1);    int3();                                   /* int3 */
            ii(0x9515, 1);    int3();                                   /* int3 */
            ii(0x9516, 1);    int3();                                   /* int3 */
            ii(0x9517, 1);    int3();                                   /* int3 */
            ii(0x9518, 1);    int3();                                   /* int3 */
            ii(0x9519, 1);    int3();                                   /* int3 */
            ii(0x951a, 1);    int3();                                   /* int3 */
            ii(0x951b, 1);    int3();                                   /* int3 */
            ii(0x951c, 1);    int3();                                   /* int3 */
            ii(0x951d, 1);    int3();                                   /* int3 */
            ii(0x951e, 1);    int3();                                   /* int3 */
            ii(0x951f, 1);    int3();                                   /* int3 */
            ii(0x9520, 1);    int3();                                   /* int3 */
            ii(0x9521, 1);    int3();                                   /* int3 */
            ii(0x9522, 1);    int3();                                   /* int3 */
            ii(0x9523, 1);    int3();                                   /* int3 */
            ii(0x9524, 1);    int3();                                   /* int3 */
            ii(0x9525, 1);    int3();                                   /* int3 */
            ii(0x9526, 1);    int3();                                   /* int3 */
            ii(0x9527, 1);    int3();                                   /* int3 */
            ii(0x9528, 1);    int3();                                   /* int3 */
            ii(0x9529, 1);    int3();                                   /* int3 */
            ii(0x952a, 1);    int3();                                   /* int3 */
            ii(0x952b, 1);    int3();                                   /* int3 */
            ii(0x952c, 1);    int3();                                   /* int3 */
            ii(0x952d, 1);    int3();                                   /* int3 */
            ii(0x952e, 1);    int3();                                   /* int3 */
            ii(0x952f, 1);    int3();                                   /* int3 */
            ii(0x9530, 1);    int3();                                   /* int3 */
            ii(0x9531, 1);    int3();                                   /* int3 */
            ii(0x9532, 1);    int3();                                   /* int3 */
            ii(0x9533, 1);    int3();                                   /* int3 */
            ii(0x9534, 1);    int3();                                   /* int3 */
            ii(0x9535, 1);    int3();                                   /* int3 */
            ii(0x9536, 1);    int3();                                   /* int3 */
            ii(0x9537, 1);    int3();                                   /* int3 */
            ii(0x9538, 1);    int3();                                   /* int3 */
            ii(0x9539, 1);    int3();                                   /* int3 */
            ii(0x953a, 1);    int3();                                   /* int3 */
            ii(0x953b, 1);    int3();                                   /* int3 */
            ii(0x953c, 1);    int3();                                   /* int3 */
            ii(0x953d, 1);    int3();                                   /* int3 */
            ii(0x953e, 1);    int3();                                   /* int3 */
            ii(0x953f, 1);    int3();                                   /* int3 */
            ii(0x9540, 1);    int3();                                   /* int3 */
            ii(0x9541, 1);    int3();                                   /* int3 */
            ii(0x9542, 1);    int3();                                   /* int3 */
            ii(0x9543, 1);    int3();                                   /* int3 */
            ii(0x9544, 1);    int3();                                   /* int3 */
            ii(0x9545, 1);    int3();                                   /* int3 */
            ii(0x9546, 1);    int3();                                   /* int3 */
            ii(0x9547, 1);    int3();                                   /* int3 */
            ii(0x9548, 1);    int3();                                   /* int3 */
            ii(0x9549, 1);    int3();                                   /* int3 */
            ii(0x954a, 1);    int3();                                   /* int3 */
            ii(0x954b, 1);    int3();                                   /* int3 */
            ii(0x954c, 1);    int3();                                   /* int3 */
            ii(0x954d, 1);    int3();                                   /* int3 */
            ii(0x954e, 1);    int3();                                   /* int3 */
            ii(0x954f, 1);    int3();                                   /* int3 */
            ii(0x9550, 1);    int3();                                   /* int3 */
            ii(0x9551, 1);    int3();                                   /* int3 */
            ii(0x9552, 1);    int3();                                   /* int3 */
            ii(0x9553, 1);    int3();                                   /* int3 */
            ii(0x9554, 1);    int3();                                   /* int3 */
            ii(0x9555, 1);    int3();                                   /* int3 */
            ii(0x9556, 1);    int3();                                   /* int3 */
            ii(0x9557, 1);    int3();                                   /* int3 */
            ii(0x9558, 1);    int3();                                   /* int3 */
            ii(0x9559, 1);    int3();                                   /* int3 */
            ii(0x955a, 1);    int3();                                   /* int3 */
            ii(0x955b, 1);    int3();                                   /* int3 */
            ii(0x955c, 1);    int3();                                   /* int3 */
            ii(0x955d, 1);    int3();                                   /* int3 */
            ii(0x955e, 1);    int3();                                   /* int3 */
            ii(0x955f, 1);    int3();                                   /* int3 */
            ii(0x9560, 1);    int3();                                   /* int3 */
            ii(0x9561, 1);    int3();                                   /* int3 */
            ii(0x9562, 1);    int3();                                   /* int3 */
            ii(0x9563, 1);    int3();                                   /* int3 */
            ii(0x9564, 1);    int3();                                   /* int3 */
            ii(0x9565, 1);    int3();                                   /* int3 */
            ii(0x9566, 1);    int3();                                   /* int3 */
            ii(0x9567, 1);    int3();                                   /* int3 */
            ii(0x9568, 1);    int3();                                   /* int3 */
            ii(0x9569, 1);    int3();                                   /* int3 */
            ii(0x956a, 1);    int3();                                   /* int3 */
            ii(0x956b, 1);    int3();                                   /* int3 */
            ii(0x956c, 1);    int3();                                   /* int3 */
            ii(0x956d, 1);    int3();                                   /* int3 */
            ii(0x956e, 1);    int3();                                   /* int3 */
            ii(0x956f, 1);    int3();                                   /* int3 */
            ii(0x9570, 1);    int3();                                   /* int3 */
            ii(0x9571, 1);    int3();                                   /* int3 */
            ii(0x9572, 1);    int3();                                   /* int3 */
            ii(0x9573, 1);    int3();                                   /* int3 */
            ii(0x9574, 1);    int3();                                   /* int3 */
            ii(0x9575, 1);    int3();                                   /* int3 */
            ii(0x9576, 1);    int3();                                   /* int3 */
            ii(0x9577, 1);    int3();                                   /* int3 */
            ii(0x9578, 1);    int3();                                   /* int3 */
            ii(0x9579, 1);    int3();                                   /* int3 */
            ii(0x957a, 1);    int3();                                   /* int3 */
            ii(0x957b, 1);    int3();                                   /* int3 */
            ii(0x957c, 1);    int3();                                   /* int3 */
            ii(0x957d, 1);    int3();                                   /* int3 */
            ii(0x957e, 1);    int3();                                   /* int3 */
            ii(0x957f, 1);    int3();                                   /* int3 */
            ii(0x9580, 1);    int3();                                   /* int3 */
            ii(0x9581, 1);    int3();                                   /* int3 */
            ii(0x9582, 1);    int3();                                   /* int3 */
            ii(0x9583, 1);    int3();                                   /* int3 */
            ii(0x9584, 1);    int3();                                   /* int3 */
            ii(0x9585, 1);    int3();                                   /* int3 */
            ii(0x9586, 1);    int3();                                   /* int3 */
            ii(0x9587, 1);    int3();                                   /* int3 */
            ii(0x9588, 1);    int3();                                   /* int3 */
            ii(0x9589, 1);    int3();                                   /* int3 */
            ii(0x958a, 1);    int3();                                   /* int3 */
            ii(0x958b, 1);    int3();                                   /* int3 */
            ii(0x958c, 1);    int3();                                   /* int3 */
            ii(0x958d, 1);    int3();                                   /* int3 */
            ii(0x958e, 1);    int3();                                   /* int3 */
            ii(0x958f, 1);    int3();                                   /* int3 */
            ii(0x9590, 1);    int3();                                   /* int3 */
            ii(0x9591, 1);    int3();                                   /* int3 */
            ii(0x9592, 1);    int3();                                   /* int3 */
            ii(0x9593, 1);    int3();                                   /* int3 */
            ii(0x9594, 1);    int3();                                   /* int3 */
            ii(0x9595, 1);    int3();                                   /* int3 */
            ii(0x9596, 1);    int3();                                   /* int3 */
            ii(0x9597, 1);    int3();                                   /* int3 */
            ii(0x9598, 1);    int3();                                   /* int3 */
            ii(0x9599, 1);    int3();                                   /* int3 */
            ii(0x959a, 1);    int3();                                   /* int3 */
            ii(0x959b, 1);    int3();                                   /* int3 */
            ii(0x959c, 1);    int3();                                   /* int3 */
            ii(0x959d, 1);    int3();                                   /* int3 */
            ii(0x959e, 1);    int3();                                   /* int3 */
            ii(0x959f, 1);    int3();                                   /* int3 */
            ii(0x95a0, 1);    int3();                                   /* int3 */
            ii(0x95a1, 1);    int3();                                   /* int3 */
            ii(0x95a2, 1);    int3();                                   /* int3 */
            ii(0x95a3, 1);    int3();                                   /* int3 */
            ii(0x95a4, 1);    int3();                                   /* int3 */
            ii(0x95a5, 1);    int3();                                   /* int3 */
            ii(0x95a6, 1);    int3();                                   /* int3 */
            ii(0x95a7, 1);    int3();                                   /* int3 */
            ii(0x95a8, 1);    int3();                                   /* int3 */
            ii(0x95a9, 1);    int3();                                   /* int3 */
            ii(0x95aa, 1);    int3();                                   /* int3 */
            ii(0x95ab, 1);    int3();                                   /* int3 */
            ii(0x95ac, 1);    int3();                                   /* int3 */
            ii(0x95ad, 1);    int3();                                   /* int3 */
            ii(0x95ae, 1);    int3();                                   /* int3 */
            ii(0x95af, 1);    int3();                                   /* int3 */
            ii(0x95b0, 1);    int3();                                   /* int3 */
            ii(0x95b1, 1);    int3();                                   /* int3 */
            ii(0x95b2, 1);    int3();                                   /* int3 */
            ii(0x95b3, 1);    int3();                                   /* int3 */
            ii(0x95b4, 1);    int3();                                   /* int3 */
            ii(0x95b5, 1);    int3();                                   /* int3 */
            ii(0x95b6, 1);    int3();                                   /* int3 */
            ii(0x95b7, 1);    int3();                                   /* int3 */
            ii(0x95b8, 1);    int3();                                   /* int3 */
            ii(0x95b9, 1);    int3();                                   /* int3 */
            ii(0x95ba, 1);    int3();                                   /* int3 */
            ii(0x95bb, 1);    int3();                                   /* int3 */
            ii(0x95bc, 1);    int3();                                   /* int3 */
            ii(0x95bd, 1);    int3();                                   /* int3 */
            ii(0x95be, 1);    int3();                                   /* int3 */
            ii(0x95bf, 1);    int3();                                   /* int3 */
            ii(0x95c0, 4);    mov(al, memb_a16[ss, bp + si + 0x51a]);   /* mov al, [bp+si+0x51a] */
            ii(0x95c4, 2);    add(memb_a16[ds, bx + si], al);           /* add [bx+si], al */
            ii(0x95c6, 3);    add(ax, 0x38);                            /* add ax, 0x38 */
            ii(0x95c9, 3);    imul(ax, ax, 0x14);                       /* imul ax, ax, 0x14 */
            ii(0x95cc, 4);    pushw(memw_a16[ds, bx + si - 0x5a44]);    /* push word [bx+si-0x5a44] */
            ii(0x95d0, 2);    add(memw_a16[ds, bx + si], ax);           /* add [bx+si], ax */
            ii(0x95d2, 3);    mov(ax, 0x47e4);                          /* mov ax, 0x47e4 */
            ii(0x95d5, 2);    add(memb_a16[ds, bx + si], al);           /* add [bx+si], al */
            ii(0x95d7, 1);    pushw(ax);                                /* push ax */
            ii(0x95d8, 3);    lea(ax, di - 0x68);                       /* lea ax, [di-0x68] */
            ii(0x95db, 1);    pushw(ax);                                /* push ax */
            ii(0x95dc, 3);    callw(0xc4bf, 0x2ee0);                    /* call 0xc4bf */
            ii(0x95df, 3);    add(ax, 0x8300);                          /* add ax, 0x8300 */
            ii(0x95e2, 2);    les(cx, ds, si);                          /* les cx, [si] */
            ii(0x95e4, 2);    xor(ax, ax);                              /* xor ax, ax */
            ii(0x95e6, 1);    pushw(ax);                                /* push ax */
            ii(0x95e7, 4);    movsx(ecx, memw_a16[ds, di - 0xc]);       /* movsx ecx, word [di-0xc] */
            ii(0x95eb, 3);    lea(bx, di - 0x68);                       /* lea bx, [di-0x68] */
            ii(0x95ee, 3);    mov(ax, memw_a16[ds, di - 0x8]);          /* mov ax, [di-0x8] */
            ii(0x95f1, 3);    inc(memw_a16[ds, di - 0x8]);              /* inc word [di-0x8] */
            ii(0x95f4, 3);    movsx(edx, ax);                           /* movsx edx, ax */
            ii(0x95f7, 3);    mov(ax, memw_a16[ds, di - 0x4]);          /* mov ax, [di-0x4] */
            ii(0x95fa, 3);    callw(0x9204, -0x3f9);                    /* call 0x9204 */
        }
    }
}
